const DEFAULT_DATE_FORMAT = 'DD.MM.YYYY';
const OUTPUT_DATE_FORMAT = 'DD MMM YYYY';
const TIME_FORMAT = 'hh:mm:ss';
const DATEPICKER_FORMAT = 'MM/DD/YYYY';
const FULL_TIME_DATE_FORMAT = `${DEFAULT_DATE_FORMAT} ${TIME_FORMAT}`
const FULL_TIME_OUTPUT_DATE_FORMAT = `${OUTPUT_DATE_FORMAT} ${TIME_FORMAT}`

export {
    DEFAULT_DATE_FORMAT,
    OUTPUT_DATE_FORMAT,
    TIME_FORMAT,
    FULL_TIME_DATE_FORMAT,
    DATEPICKER_FORMAT,
    FULL_TIME_OUTPUT_DATE_FORMAT,
}